name: Profile Summary Cards

on:
  schedule:
    # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  summary-cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Generate Profile Summary Cards
      uses: vn7n24fzkq/github-profile-summary-cards@release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        USERNAME: VINAY-KOTHARI-10
        UTC_OFFSET: 5.5
        EXCLUDE: ""