name: Update README with Latest Activity

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Update README with latest activity
      uses: jamesgeorge007/github-activity-readme@v0.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MSG: 'Update README with latest activity'
        MAX_LINES: 10

    - name: Update WakaTime stats
      uses: anmol098/waka-readme-stats@v3.0
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHOW_LINES_OF_CODE: "True"
        SHOW_PROFILE_VIEWS: "False"
        SHOW_COMMIT: "True"
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE: "True"
        SHOW_OS: "True"
        SHOW_PROJECTS: "True"
        SHOW_TIMEZONE: "True"
        SHOW_EDITORS: "True"
        SHOW_LANGUAGE_PER_REPO: "True"
        SHOW_SHORT_INFO: "True"
        SHOW_LOC_CHART: "True"
